# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TapAdditionsKitV2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TapAdditionsKitV2
  pod 'SwiftLint'
  pod 'TapSwiftFixes/Exceptions'
  pod 'TapSwiftFixes/Threading'

end
